version: '2'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3308:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: vap
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: "@Admin12345"
  vap-go:
    volumes:
      - .:/app:cached
    ports:
      - 3000:3000
    links:
      - mysql
    depends_on:
      - mysql
    build: .
volumes:
  data:
    driver: local